const Res_LIST = [
    {
      info: {
        id: "263954",
        name: "Chai Point",
        cloudinaryImageId: "znobbbace3njt7oxau2f",
        locality: "Adb Pwd Colony",
        areaName: "Sector 16",
        costForTwo: "₹150 for two",
        cuisines: [
          "Bakery",
          "Beverages",
          "Maharashtrian",
          "Snacks",
          "Street Food",
          "South Indian",
          "Punjabi",
          "Chaat",
          "Indian",
          "American",
          "North Indian",
          "Fast Food",
          "Desserts",
          "Cafe",
          "Healthy Food",
          "Home Food",
        ],
        avgRating: 4.1,
        feeDetails: {
          restaurantId: "263954",
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4000,
            },
            {
              name: "BASE_TIME",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
            },
          ],
          totalFee: 4000,
        },
        parentId: "1607",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 18,
          lastMileTravel: 0.2,
          serviceability: "SERVICEABLE",
          slaString: "18 mins",
          lastMileTravelString: "0.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-08-28 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
        },
        loyaltyDiscoverPresentationInfo: {
          badgeType: "BADGE_TYPE_OFFER_PACK",
          offerSubText: "with offer pack",
          nonSwiggyOneFreedelMessage: "FREE DELIVERY",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/chai-point-adb-pwd-colony-sector-16-faridabad-263954",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "353657",
        name: "Chaayos Chai+Snacks=Relax",
        cloudinaryImageId: "2beebd3688e63e027ee8a11c1c8a72c8",
        locality: "Shopping Centre Market",
        areaName: "Sector 15",
        costForTwo: "₹250 for two",
        cuisines: [
          "Bakery",
          "Beverages",
          "Chaat",
          "Desserts",
          "Home Food",
          "Italian",
          "Maharashtrian",
          "Snacks",
          "Street Food",
          "Sweets",
        ],
        avgRating: 4.1,
        feeDetails: {
          restaurantId: "353657",
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4000,
            },
            {
              name: "BASE_TIME",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
            },
          ],
          totalFee: 4000,
        },
        parentId: "281782",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 20,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "20 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-08-28 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹100",
        },
        loyaltyDiscoverPresentationInfo: {
          badgeType: "BADGE_TYPE_OFFER_PACK",
          offerSubText: "with offer pack",
          nonSwiggyOneFreedelMessage: "FREE DELIVERY",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/chaayos-chai-snacks-relax-shopping-centre-market-sector-15-faridabad-353657",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "39278",
        name: "Faasos - Wraps & Rolls",
        cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
        locality: "Kapori Colony",
        areaName: "Sector 19",
        costForTwo: "₹200 for two",
        cuisines: [
          "Kebabs",
          "Fast Food",
          "Snacks",
          "North Indian",
          "American",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4,
        feeDetails: {
          restaurantId: "39278",
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4000,
            },
            {
              name: "BASE_TIME",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
            },
          ],
          totalFee: 4000,
        },
        parentId: "21809",
        avgRatingString: "4.0",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 1.3,
          serviceability: "SERVICEABLE",
          slaString: "28 mins",
          lastMileTravelString: "1.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-08-22 03:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹100",
        },
        loyaltyDiscoverPresentationInfo: {
          badgeType: "BADGE_TYPE_OFFER_PACK",
          offerSubText: "with offer pack",
          nonSwiggyOneFreedelMessage: "FREE DELIVERY",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/faasos-wraps-and-rolls-kapori-colony-sector-19-faridabad-39278",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "62981",
        name: "LunchBox - Meals and Thalis",
        cloudinaryImageId: "cyxvct5xkqlxkqth4sh0",
        locality: "Kapori Colony",
        areaName: "Sector 19",
        costForTwo: "₹200 for two",
        cuisines: [
          "Biryani",
          "North Indian",
          "Punjabi",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4,
        feeDetails: {
          restaurantId: "62981",
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4000,
            },
            {
              name: "BASE_TIME",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
            },
          ],
          totalFee: 4000,
        },
        parentId: "4925",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 26,
          lastMileTravel: 1.3,
          serviceability: "SERVICEABLE",
          slaString: "26 mins",
          lastMileTravelString: "1.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-08-22 03:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹100",
        },
        loyaltyDiscoverPresentationInfo: {
          badgeType: "BADGE_TYPE_OFFER_PACK",
          offerSubText: "with offer pack",
          nonSwiggyOneFreedelMessage: "FREE DELIVERY",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/lunchbox-meals-and-thalis-kapori-colony-sector-19-faridabad-62981",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "242351",
        name: "Sweet Truth - Cake and Desserts",
        cloudinaryImageId: "4a3b48488e3aa9bda13efd8cfcd95284",
        locality: "Rani Bhawan",
        areaName: "New Industrial Township",
        costForTwo: "₹450 for two",
        cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
        avgRating: 3.9,
        feeDetails: {
          restaurantId: "242351",
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 5200,
            },
            {
              name: "BASE_TIME",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
            },
          ],
          totalFee: 5200,
        },
        parentId: "4444",
        avgRatingString: "3.9",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 31,
          lastMileTravel: 4.7,
          serviceability: "SERVICEABLE",
          slaString: "31 mins",
          lastMileTravelString: "4.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-08-22 01:45:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹100",
        },
        loyaltyDiscoverPresentationInfo: {
          badgeType: "BADGE_TYPE_OFFER_PACK",
          offerSubText: "with offer pack",
          nonSwiggyOneFreedelMessage: "FREE DELIVERY",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/sweet-truth-cake-and-desserts-rani-bhawan-new-industrial-township-faridabad-242351",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "148645",
        name: "Hunger Cure (Pure Veg)",
        cloudinaryImageId: "vgekitzjwk1r63uxneov",
        locality: "Sector-79",
        areaName: "Omaxe World Street",
        costForTwo: "₹300 for two",
        cuisines: [
          "North Indian",
          "Chinese",
          "Burgers",
          "Pastas",
          "Pizzas",
          "Fast Food",
          "Snacks",
          "Beverages",
          "Continental",
          "Indian",
          "Italian",
          "American",
        ],
        avgRating: 4.1,
        feeDetails: {
          restaurantId: "148645",
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 5800,
            },
            {
              name: "BASE_TIME",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
            },
          ],
          totalFee: 5800,
        },
        parentId: "15316",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 5.5,
          serviceability: "SERVICEABLE",
          slaString: "35 mins",
          lastMileTravelString: "5.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-08-21 22:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        loyaltyDiscoverPresentationInfo: {
          badgeType: "BADGE_TYPE_OFFER_PACK",
          offerSubText: "with offer pack",
          nonSwiggyOneFreedelMessage: "FREE DELIVERY",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/hunger-cure-pure-veg-sector-79-omaxe-world-street-faridabad-148645",
        type: "WEBLINK",
      },
    },
  ];
  export default Res_LIST;